// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Tips_location_down.pb.h"
// @@protoc_insertion_point(imports)

@implementation TipsLocationDownRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [TipsLocationDownRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface tips_location_down ()
@property tips_location_downdata_type type;
@property (strong) NSString* location;
@property (strong) NSData* key;
@end

@implementation tips_location_down

- (BOOL) hasType {
  return !!hasType_;
}
- (void) setHasType:(BOOL) value_ {
  hasType_ = !!value_;
}
@synthesize type;
- (BOOL) hasLocation {
  return !!hasLocation_;
}
- (void) setHasLocation:(BOOL) value_ {
  hasLocation_ = !!value_;
}
@synthesize location;
- (BOOL) hasKey {
  return !!hasKey_;
}
- (void) setHasKey:(BOOL) value_ {
  hasKey_ = !!value_;
}
@synthesize key;
- (id) init {
  if ((self = [super init])) {
    self.type = tips_location_downdata_typeDivergenceUs;
    self.location = @"";
    self.key = [NSData data];
  }
  return self;
}
static tips_location_down* defaulttips_location_downInstance = nil;
+ (void) initialize {
  if (self == [tips_location_down class]) {
    defaulttips_location_downInstance = [[tips_location_down alloc] init];
  }
}
+ (tips_location_down*) defaultInstance {
  return defaulttips_location_downInstance;
}
- (tips_location_down*) defaultInstance {
  return defaulttips_location_downInstance;
}
- (BOOL) isInitialized {
  if (!self.hasType) {
    return NO;
  }
  if (!self.hasLocation) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasType) {
    [output writeEnum:1 value:self.type];
  }
  if (self.hasLocation) {
    [output writeString:2 value:self.location];
  }
  if (self.hasKey) {
    [output writeData:3 value:self.key];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasType) {
    size_ += computeEnumSize(1, self.type);
  }
  if (self.hasLocation) {
    size_ += computeStringSize(2, self.location);
  }
  if (self.hasKey) {
    size_ += computeDataSize(3, self.key);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (tips_location_down*) parseFromData:(NSData*) data {
  return (tips_location_down*)[[[tips_location_down builder] mergeFromData:data] build];
}
+ (tips_location_down*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (tips_location_down*)[[[tips_location_down builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (tips_location_down*) parseFromInputStream:(NSInputStream*) input {
  return (tips_location_down*)[[[tips_location_down builder] mergeFromInputStream:input] build];
}
+ (tips_location_down*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (tips_location_down*)[[[tips_location_down builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (tips_location_down*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (tips_location_down*)[[[tips_location_down builder] mergeFromCodedInputStream:input] build];
}
+ (tips_location_down*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (tips_location_down*)[[[tips_location_down builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (tips_location_downBuilder*) builder {
  return [[tips_location_downBuilder alloc] init];
}
+ (tips_location_downBuilder*) builderWithPrototype:(tips_location_down*) prototype {
  return [[tips_location_down builder] mergeFrom:prototype];
}
- (tips_location_downBuilder*) builder {
  return [tips_location_down builder];
}
- (tips_location_downBuilder*) toBuilder {
  return [tips_location_down builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasType) {
    [output appendFormat:@"%@%@: %@\n", indent, @"type", [NSNumber numberWithInteger:self.type]];
  }
  if (self.hasLocation) {
    [output appendFormat:@"%@%@: %@\n", indent, @"location", self.location];
  }
  if (self.hasKey) {
    [output appendFormat:@"%@%@: %@\n", indent, @"key", self.key];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[tips_location_down class]]) {
    return NO;
  }
  tips_location_down *otherMessage = other;
  return
      self.hasType == otherMessage.hasType &&
      (!self.hasType || self.type == otherMessage.type) &&
      self.hasLocation == otherMessage.hasLocation &&
      (!self.hasLocation || [self.location isEqual:otherMessage.location]) &&
      self.hasKey == otherMessage.hasKey &&
      (!self.hasKey || [self.key isEqual:otherMessage.key]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasType) {
    hashCode = hashCode * 31 + self.type;
  }
  if (self.hasLocation) {
    hashCode = hashCode * 31 + [self.location hash];
  }
  if (self.hasKey) {
    hashCode = hashCode * 31 + [self.key hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

BOOL tips_location_downdata_typeIsValidValue(tips_location_downdata_type value) {
  switch (value) {
    case tips_location_downdata_typeDivergenceUs:
    case tips_location_downdata_typeDivergenceTw:
    case tips_location_downdata_typeDivergenceCn:
    case tips_location_downdata_typeDivergenceHk:
    case tips_location_downdata_typePatternUs:
    case tips_location_downdata_typePatternTw:
    case tips_location_downdata_typePatternCn:
    case tips_location_downdata_typePatternHk:
      return YES;
    default:
      return NO;
  }
}
@interface tips_location_downBuilder()
@property (strong) tips_location_down* result;
@end

@implementation tips_location_downBuilder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[tips_location_down alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (tips_location_downBuilder*) clear {
  self.result = [[tips_location_down alloc] init];
  return self;
}
- (tips_location_downBuilder*) clone {
  return [tips_location_down builderWithPrototype:result];
}
- (tips_location_down*) defaultInstance {
  return [tips_location_down defaultInstance];
}
- (tips_location_down*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (tips_location_down*) buildPartial {
  tips_location_down* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (tips_location_downBuilder*) mergeFrom:(tips_location_down*) other {
  if (other == [tips_location_down defaultInstance]) {
    return self;
  }
  if (other.hasType) {
    [self setType:other.type];
  }
  if (other.hasLocation) {
    [self setLocation:other.location];
  }
  if (other.hasKey) {
    [self setKey:other.key];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (tips_location_downBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (tips_location_downBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        tips_location_downdata_type value = (tips_location_downdata_type)[input readEnum];
        if (tips_location_downdata_typeIsValidValue(value)) {
          [self setType:value];
        } else {
          [unknownFields mergeVarintField:1 value:value];
        }
        break;
      }
      case 18: {
        [self setLocation:[input readString]];
        break;
      }
      case 26: {
        [self setKey:[input readData]];
        break;
      }
    }
  }
}
- (BOOL) hasType {
  return result.hasType;
}
- (tips_location_downdata_type) type {
  return result.type;
}
- (tips_location_downBuilder*) setType:(tips_location_downdata_type) value {
  result.hasType = YES;
  result.type = value;
  return self;
}
- (tips_location_downBuilder*) clearType {
  result.hasType = NO;
  result.type = tips_location_downdata_typeDivergenceUs;
  return self;
}
- (BOOL) hasLocation {
  return result.hasLocation;
}
- (NSString*) location {
  return result.location;
}
- (tips_location_downBuilder*) setLocation:(NSString*) value {
  result.hasLocation = YES;
  result.location = value;
  return self;
}
- (tips_location_downBuilder*) clearLocation {
  result.hasLocation = NO;
  result.location = @"";
  return self;
}
- (BOOL) hasKey {
  return result.hasKey;
}
- (NSData*) key {
  return result.key;
}
- (tips_location_downBuilder*) setKey:(NSData*) value {
  result.hasKey = YES;
  result.key = value;
  return self;
}
- (tips_location_downBuilder*) clearKey {
  result.hasKey = NO;
  result.key = [NSData data];
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
