// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Tips_location_up.pb.h"
// @@protoc_insertion_point(imports)

@implementation TipsLocationUpRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [TipsLocationUpRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface tips_location_up ()
@property tips_location_updata_type type;
@end

@implementation tips_location_up

- (BOOL) hasType {
  return !!hasType_;
}
- (void) setHasType:(BOOL) value_ {
  hasType_ = !!value_;
}
@synthesize type;
- (id) init {
  if ((self = [super init])) {
    self.type = tips_location_updata_typeDivergenceUs;
  }
  return self;
}
static tips_location_up* defaulttips_location_upInstance = nil;
+ (void) initialize {
  if (self == [tips_location_up class]) {
    defaulttips_location_upInstance = [[tips_location_up alloc] init];
  }
}
+ (tips_location_up*) defaultInstance {
  return defaulttips_location_upInstance;
}
- (tips_location_up*) defaultInstance {
  return defaulttips_location_upInstance;
}
- (BOOL) isInitialized {
  if (!self.hasType) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasType) {
    [output writeEnum:1 value:self.type];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasType) {
    size_ += computeEnumSize(1, self.type);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (tips_location_up*) parseFromData:(NSData*) data {
  return (tips_location_up*)[[[tips_location_up builder] mergeFromData:data] build];
}
+ (tips_location_up*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (tips_location_up*)[[[tips_location_up builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (tips_location_up*) parseFromInputStream:(NSInputStream*) input {
  return (tips_location_up*)[[[tips_location_up builder] mergeFromInputStream:input] build];
}
+ (tips_location_up*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (tips_location_up*)[[[tips_location_up builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (tips_location_up*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (tips_location_up*)[[[tips_location_up builder] mergeFromCodedInputStream:input] build];
}
+ (tips_location_up*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (tips_location_up*)[[[tips_location_up builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (tips_location_upBuilder*) builder {
  return [[tips_location_upBuilder alloc] init];
}
+ (tips_location_upBuilder*) builderWithPrototype:(tips_location_up*) prototype {
  return [[tips_location_up builder] mergeFrom:prototype];
}
- (tips_location_upBuilder*) builder {
  return [tips_location_up builder];
}
- (tips_location_upBuilder*) toBuilder {
  return [tips_location_up builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasType) {
    [output appendFormat:@"%@%@: %@\n", indent, @"type", [NSNumber numberWithInteger:self.type]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[tips_location_up class]]) {
    return NO;
  }
  tips_location_up *otherMessage = other;
  return
      self.hasType == otherMessage.hasType &&
      (!self.hasType || self.type == otherMessage.type) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasType) {
    hashCode = hashCode * 31 + self.type;
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

BOOL tips_location_updata_typeIsValidValue(tips_location_updata_type value) {
  switch (value) {
    case tips_location_updata_typeDivergenceUs:
    case tips_location_updata_typeDivergenceTw:
    case tips_location_updata_typeDivergenceCn:
    case tips_location_updata_typeDivergenceHk:
    case tips_location_updata_typePatternUs:
    case tips_location_updata_typePatternTw:
    case tips_location_updata_typePatternCn:
    case tips_location_updata_typePatternHk:
      return YES;
    default:
      return NO;
  }
}
@interface tips_location_upBuilder()
@property (strong) tips_location_up* result;
@end

@implementation tips_location_upBuilder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[tips_location_up alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (tips_location_upBuilder*) clear {
  self.result = [[tips_location_up alloc] init];
  return self;
}
- (tips_location_upBuilder*) clone {
  return [tips_location_up builderWithPrototype:result];
}
- (tips_location_up*) defaultInstance {
  return [tips_location_up defaultInstance];
}
- (tips_location_up*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (tips_location_up*) buildPartial {
  tips_location_up* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (tips_location_upBuilder*) mergeFrom:(tips_location_up*) other {
  if (other == [tips_location_up defaultInstance]) {
    return self;
  }
  if (other.hasType) {
    [self setType:other.type];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (tips_location_upBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (tips_location_upBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        tips_location_updata_type value = (tips_location_updata_type)[input readEnum];
        if (tips_location_updata_typeIsValidValue(value)) {
          [self setType:value];
        } else {
          [unknownFields mergeVarintField:1 value:value];
        }
        break;
      }
    }
  }
}
- (BOOL) hasType {
  return result.hasType;
}
- (tips_location_updata_type) type {
  return result.type;
}
- (tips_location_upBuilder*) setType:(tips_location_updata_type) value {
  result.hasType = YES;
  result.type = value;
  return self;
}
- (tips_location_upBuilder*) clearType {
  result.hasType = NO;
  result.type = tips_location_updata_typeDivergenceUs;
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
