// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class tips_location_up;
@class tips_location_upBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif

typedef NS_ENUM(SInt32, tips_location_updata_type) {
  tips_location_updata_typeDivergenceUs = 0,
  tips_location_updata_typeDivergenceTw = 1,
  tips_location_updata_typeDivergenceCn = 2,
  tips_location_updata_typeDivergenceHk = 3,
  tips_location_updata_typePatternUs = 4,
  tips_location_updata_typePatternTw = 5,
  tips_location_updata_typePatternCn = 6,
  tips_location_updata_typePatternHk = 7,
};

BOOL tips_location_updata_typeIsValidValue(tips_location_updata_type value);


@interface TipsLocationUpRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface tips_location_up : PBGeneratedMessage {
@private
  BOOL hasType_:1;
  tips_location_updata_type type;
}
- (BOOL) hasType;
@property (readonly) tips_location_updata_type type;

+ (tips_location_up*) defaultInstance;
- (tips_location_up*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (tips_location_upBuilder*) builder;
+ (tips_location_upBuilder*) builder;
+ (tips_location_upBuilder*) builderWithPrototype:(tips_location_up*) prototype;
- (tips_location_upBuilder*) toBuilder;

+ (tips_location_up*) parseFromData:(NSData*) data;
+ (tips_location_up*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tips_location_up*) parseFromInputStream:(NSInputStream*) input;
+ (tips_location_up*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (tips_location_up*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (tips_location_up*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface tips_location_upBuilder : PBGeneratedMessageBuilder {
@private
  tips_location_up* result;
}

- (tips_location_up*) defaultInstance;

- (tips_location_upBuilder*) clear;
- (tips_location_upBuilder*) clone;

- (tips_location_up*) build;
- (tips_location_up*) buildPartial;

- (tips_location_upBuilder*) mergeFrom:(tips_location_up*) other;
- (tips_location_upBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (tips_location_upBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (tips_location_updata_type) type;
- (tips_location_upBuilder*) setType:(tips_location_updata_type) value;
- (tips_location_upBuilder*) clearType;
@end


// @@protoc_insertion_point(global_scope)
